#!/usr/bin/env bash
set -e

PACKET_GROUP=''
PACKET=''
while [[ $# -gt 0 ]]; do
    case "$1" in
        --role)
            ROLE="$2"
            shift 2
            ;;
        --permission)
            PERMISSION="$2"
            shift 2
            ;;
        --packet-group)
            PACKET_GROUP="$2"
            shift 2
            ;;
        --packet-id)
            PACKET="$2"
            shift 2
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
done

if [[ -n "$PACKET" ]]
then
    echo "Setting permission with packet scope"

    SQL="INSERT INTO role_permission (role_id, permission_id, packet_id)
    VALUES ((select role.id from role where role.name=:'role'), (select permission_id from permission where permission.name=:'permission'),
             :'packet');"
elif [[ -n "$PACKET_GROUP" ]]
then
    echo "Setting permission with packet group scope"

    SQL="INSERT INTO role_permission (role_id, permission_id, packet_group_id)
    VALUES ((select role.id from role where role.name=:'role'), (select permission_id from permission where permission.name=:'permission'),
             (select packet_group.id from packet_group where packet_group.name=:'packet_group'));"
else
    echo "Setting permission with global scope"

    SQL="INSERT INTO role_permission (role_id, permission_id)
    VALUES ((select role.id from role where role.name=:'role'), (select permission.id from permission where permission.name=:'permission'));"
fi

psql -U packituser -d packit \
    --single-transaction \
    -v ON_ERROR_STOP=on \
    -v "role=$ROLE" \
    -v "permission=$PERMISSION" \
    -v "packet=$PACKET" \
    -v "packet_group=$PACKET_GROUP" <<EOF
$SQL
EOF