#!/usr/bin/env bash
set -eu

psql -U packituser -d packit \
    --single-transaction \
    -v ON_ERROR_STOP=on \
    -v "username=$1" \
    -v "role=$2" <<EOF
INSERT INTO "user_role" (user_id, role_id)
VALUES ((SELECT "user".id FROM "user" WHERE "user".username=:'username'), (select role.id from role where role.name=:'role'));
EOF