#!/usr/bin/env bash
set -eu

psql -U packituser -d packit \
    --single-transaction \
    -v ON_ERROR_STOP=on \
    -v "role=$1" <<EOF
INSERT INTO "role" (name, is_username)
VALUES(:'role', FALSE);
EOF
